config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => 'products#home'

  resources :products do
    resources :reviews, :except => [:index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord

  has_many :reviews

  validates :name, :presence => true
  validates :cost, :presence => true
  validates :country_of_origin, :presence => true

  scope :recent, -> { order(created_at: :desc).limit(3) }

  scope :mostreviewed, -> { select("products.id, products.name, products.cost, products.country_of_origin, count(reviews.id) as reviews_count")
  .joins(:reviews)
  .group("products.id")
  .order("reviews_count DESC")
  .limit(1) }

  scope :domestic, -> { where(country_of_origin: "USA") }

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product

  validates :author, :presence => true
  validates :content_body, :presence => true
  validates :rating, :presence => true

  validates :content_body, length: { in: 50..250}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    if params[:sort] == "domestic"
      @products = Product.domestic
    else
      @products = Product.all
    end
  end

  def home
    @lastproducts = Product.recent
    @mostreviewed = Product.mostreviewed
  end

  def show
    @product = Product.find(params[:id])
    @reviews = @product.reviews
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = "Product successfully added!"
      redirect_to  products_path
    else
      flash[:notice] = "Please double-check your entries"
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to  products_path
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end

  private
    def product_params
      params.require(:product).permit(:name, :cost, :country_of_origin)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new
  end

  def index
    @product = Product.find(params[:id])
    @reviews = @product.reviews
  end

  def show
    @review = Review.find(params[:id])
    @products = Product.all()
  end

  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new(review_params)
    if @review.save
      redirect_to product_path(@review.product)
    else
      flash[:notice] = "Make sure your review is between 50 & 250 characters"
      render :new
    end
  end

  def edit
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    render :edit
  end

  def update
    @review = Review.find(params[:id])
    @product = @review.product
    if @review.update(review_params)
      redirect_to product_path(@product)
    else
      render 'reviews/edit'
    end
  end

  def destroy
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to product_path(@product)
  end

  private
    def review_params
      params.require(:review).permit(:auhtor, :content_body, :rating, :product_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FoodProductRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= flash[:notice] %>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_for @product do |p| %>
  <%= p.label :name %>
  <%= p.text_field :name %>

  <%= p.label :cost %>
  <%= p.number_field(:cost, in: 1.0..100.0) %>


  <%= p.label :country_of_origin %>
  <%= p.text_field :country_of_origin %>

  <%= p.submit %>
<% end %>

app/views/products/home.html.erb
<% content_for(:name, "Products") %>
<h1>This is the landing page</h1>

<h2>These are the currently featured products</h2>

<% @lastproducts.each do |product| %>
  <div class="well"><%= link_to product.name, product_path(product) %> </div>
<% end %>


<hr>
<h2>This is the most reviewed product</h2>


<div class="well"><%= link_to @mostreviewed.name, product_path(@mostreviewed) %> </div>

app/views/products/index.html.erb
<% content_for(:name, "Products") %>

<div class="container">
  <h1>Products</h1>

  <a href="?sort=domestic"><button class="btn">Domestic Products</button></a>
  <button class="btn"><%= link_to "All Products", products_path %></button>

    <% @products.each do |product| %>
      <div class="well"><%= link_to product.name, product_path(product) %> </div>
      <% end %>


  <%= link_to "New Product", new_product_path %>
</div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render "form" %>

app/views/products/show.html.erb
<% content_for(:name, @product.name) %>
<h1><%= @product.name %></h1>

<% if @product.reviews.any? %>
  <% @product.reviews.each do |review| %>
    <p>
      <%= link_to review.author, product_review_path(@product, review)%>,
    </p>
  <% end %>
<% else %>
  <p>There are no reviews yet!</p>
<% end %>

<%= link_to "Add Review", new_product_review_path(@product) %>

<%= render "form" %>

<h3><a href="/products">Products</a></h3>

<%= link_to "Delete", product_path(@product),
                                 :data => {:confirm => "Are you sure?",
                                                    :method => "delete"} %>

app/views/reviews/_form.html.erb
<div class="well">
  <div class="well-body">

    <%= form_for [@product, @review] do |f| %>
      <%= f.label :author %>
      <%= f.text_field :author %>
    <br>
      <%= f.label :content_body %>
      <%= f.text_field :content_body %>
    <br>
      <%= f.label :rating %>
      <%= radio_button_tag(:rating, "1") %>
      <%= label_tag(:rating, "1") %>
      <%= radio_button_tag(:rating, "2") %>
      <%= label_tag(:rating, "2") %>
      <%= radio_button_tag(:rating, "3") %>
      <%= label_tag(:rating, "3") %>
      <%= radio_button_tag(:rating, "4") %>
      <%= label_tag(:rating, "4") %>
      <%= radio_button_tag(:rating, "5") %>
      <%= label_tag(:rating, "5") %>
    <br>
      <%= f.submit %>
    <% end %>

  </div>
</div>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render "form" %>

app/views/reviews/show.html.erb
<% content_for(:author, @review.author) %>
<% content_for(:content_body, @review.content_body) %>
<% content_for(:rating, @review.rating) %>

<h1><%= @review.author %></h1>
<h1><%= @review.content_body %></h1>
<h1><%= @review.rating %></h1>


<h3><a href="/products">Products</a></h3>

<%= link_to "Delete", product_review_path(@review),
                                 :data => {:confirm => "Are you sure?",
                                                    :method => "delete"} %>